### PR TITLE
Add header support

### PR DESCRIPTION
**Pull request by vlasy**
Inspired by your recent authorization support, I tried to add a more generic header support.

### CODE REVIEW

**Comment by kminami** [comment]
Thank you for a contribution!

Commnets:
- The spec saids: `The list MUST NOT include duplicated parameters. A unique parameter is defined by a combination of a name and location. `
    - You MUST remove duplicated parameters like "Accept" heaeder
- parameter.description should be empty string (at least, I prefer it)

**Comment by vlasy** [comment]
Thanks for the specification info - it is now fixed.

About the `parameter.description` - if we would remove it, how would you know (e.g. in Swagger UI where the `x-example` value is not shown anywhere) what the header is supposed to contain or see some example value?

**Comment by kminami** [comment]
In Swagger UI, you can see the "x-example" value by clicking "Try it out".

My another suggestion is prefixing the `header.value` with "e.g. " or "Example value is " for `parameter.description`.
How do you think?

**Comment by vlasy** [comment]
Prefixing sounds great. That way, you can preserve more information while also complying to spec: `A brief description of the parameter. This could contain examples of use.`

**Comment by kminami** [comment]
Thank you very much!

**Comment by kminami** [comment]
Released as v1.7.0

**Pull request merged**
